/********************************************************************************
** Form generated from reading UI file 'login.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LOGIN_H
#define UI_LOGIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Login
{
public:
    QStackedWidget *ATM;
    QWidget *welkomScherm;
    QPushButton *welkom_taal_button;
    QLabel *welkom_label;
    QPushButton *welkom_inlog_button;
    QLabel *welkom_logo;
    QLabel *welkom_taal_label;
    QWidget *inlogScherm;
    QLabel *inlog_voerpin_label;
    QPushButton *inlog_taal_button;
    QPushButton *inlog_hoofd_button;
    QPushButton *inlog_welkom_button;
    QLabel *inlog_label;
    QLineEdit *inlog_invoerveldPincode;
    QLabel *inlog_logo;
    QLabel *inlog_delete;
    QLabel *inlog_taal_label;
    QLabel *inlog_delete_label;
    QLabel *inlog_hoofd_label;
    QLabel *inlog_welkom_label;
    QWidget *taalScherm;
    QPushButton *taal_optieNederlands_button;
    QPushButton *taal_optieEngels_button;
    QPushButton *taal_optieDuits_button;
    QPushButton *taal_welkom_button;
    QPushButton *taal_hoofd_of_welkom_of_inlog_button;
    QLabel *taal_duitsland_vlag;
    QLabel *taal_engeland_vlag;
    QLabel *taal_nederland_vlag;
    QLabel *taal_label;
    QLabel *taal_logo;
    QLabel *taal_nederlands_label;
    QLabel *taal_duitsland_label;
    QLabel *taal_engeland_label;
    QLabel *taal_back_label;
    QLabel *taal_welkom_label;
    QWidget *hoofdScherm;
    QLabel *hoofdLabel;
    QPushButton *hoofd_snelPinnen_button;
    QPushButton *hoofd_saldo_button;
    QPushButton *hoofd_pinKeuze_button;
    QPushButton *hoofd_taal_button;
    QPushButton *hoofd_welkom_button;
    QLabel *hoofd_logo;
    QLabel *hoofd_taal_label;
    QLabel *hoofd_snelPinnen_label;
    QLabel *hoofd_pinKeuze_label;
    QLabel *hoofd_saldo_label;
    QLabel *hoofd_welkom_label;
    QWidget *saldoScherm;
    QLabel *saldo_label_wat_is_saldo;
    QPushButton *saldo_pinKeuze_button;
    QPushButton *saldo_welkom_button;
    QPushButton *saldo_hoofdscherm_button;
    QLabel *saldo_label;
    QLabel *saldo_logo;
    QLabel *saldo_pinKeuze_label;
    QLabel *saldo_hoofdscherm_label;
    QLabel *saldo_welkom_label;
    QWidget *pinKeuzeScherm;
    QLabel *pinKeuze_label;
    QPushButton *pinKeuze_optie1_button;
    QPushButton *pinKeuze_optie2_button;
    QPushButton *pinKeuze_optie3_button;
    QPushButton *pinKeuze_optie4_button;
    QPushButton *pinKeuze_optie5_button;
    QPushButton *pinKeuze_zelfBedragKiezen_button;
    QPushButton *pinKeuze_welkom_button;
    QPushButton *pinKeuze_hoofd_button;
    QLabel *pinKeuze_logo;
    QLabel *pinKeuze_optie4_label;
    QLabel *pinKeuze_optie3_label;
    QLabel *pinKeuze_optie2_label;
    QLabel *pinKeuze_optie1_label;
    QLabel *pinKeuze_hoofd_label;
    QLabel *pinKeuze_optie5_label;
    QLabel *pinKeuze_zelfBedragKiezen_label;
    QLabel *pinKeuze_welkom_label;
    QWidget *biljetScherm;
    QLabel *biljetKeuze_label;
    QPushButton *biljetKeuze_welkom_button;
    QPushButton *biljetKeuze_hoofd_button;
    QPushButton *biljetKeuze_biljetNietBelangrijk_button;
    QPushButton *biljetKeuze_biljetOpties1_button;
    QLabel *biljetKeuze_logo;
    QLabel *biljetKeuze_hoofd_label;
    QLabel *biljetKeuze_biljetNietBelangrijk_label;
    QLabel *biljetKeuze_biljetOpties1_label;
    QLabel *biljetKeuze_welkom_label;
    QWidget *bedragScherm;
    QLabel *bedrag_label;
    QPushButton *bedragKeuze_hoofd_button;
    QPushButton *bedragKeuze_welkom_button;
    QPushButton *bedragKeuze_bevestigen_button;
    QLineEdit *bedragKeuze_invoerVeld;
    QLabel *bedragKeuze_error_label;
    QLabel *bedragKeuze_logo;
    QLabel *bedragKeuze_bevestigen_label;
    QLabel *bedragKeuze_hoofd_label;
    QLabel *bedragKeuze_welkom_label;
    QWidget *bonScherm;
    QLabel *bon_label;
    QPushButton *bon_metBon_button;
    QPushButton *bon_zonderBon_button;
    QPushButton *bon_hoofd_button;
    QPushButton *bon_welkom_button;
    QLabel *bon_logo;
    QLabel *bon_hoofd_label;
    QLabel *bon_metBon_label;
    QLabel *bon_welkom_label;
    QLabel *bon_zonderBon_label;
    QWidget *verwerkingsScherm;
    QLabel *verwerkings_label;
    QLabel *verwerkings_logo;
    QProgressBar *verwerkings_laadbalk;

    void setupUi(QWidget *Login)
    {
        if (Login->objectName().isEmpty())
            Login->setObjectName(QString::fromUtf8("Login"));
        Login->setEnabled(true);
        Login->resize(1284, 760);
        ATM = new QStackedWidget(Login);
        ATM->setObjectName(QString::fromUtf8("ATM"));
        ATM->setGeometry(QRect(10, 10, 1261, 741));
        QFont font;
        font.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        ATM->setFont(font);
        ATM->setAutoFillBackground(true);
        ATM->setFrameShape(QFrame::Panel);
        welkomScherm = new QWidget();
        welkomScherm->setObjectName(QString::fromUtf8("welkomScherm"));
        welkom_taal_button = new QPushButton(welkomScherm);
        welkom_taal_button->setObjectName(QString::fromUtf8("welkom_taal_button"));
        welkom_taal_button->setGeometry(QRect(950, 40, 201, 101));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(welkom_taal_button->sizePolicy().hasHeightForWidth());
        welkom_taal_button->setSizePolicy(sizePolicy);
        QFont font1;
        font1.setPointSize(14);
        welkom_taal_button->setFont(font1);
        welkom_label = new QLabel(welkomScherm);
        welkom_label->setObjectName(QString::fromUtf8("welkom_label"));
        welkom_label->setGeometry(QRect(540, 270, 181, 161));
        QFont font2;
        font2.setPointSize(18);
        font2.setUnderline(false);
        font2.setStrikeOut(false);
        font2.setKerning(true);
        welkom_label->setFont(font2);
        welkom_label->setAutoFillBackground(false);
        welkom_label->setScaledContents(false);
        welkom_label->setAlignment(Qt::AlignCenter);
        welkom_label->setWordWrap(true);
        welkom_label->setOpenExternalLinks(false);
        welkom_inlog_button = new QPushButton(welkomScherm);
        welkom_inlog_button->setObjectName(QString::fromUtf8("welkom_inlog_button"));
        welkom_inlog_button->setGeometry(QRect(1060, 630, 171, 81));
        sizePolicy.setHeightForWidth(welkom_inlog_button->sizePolicy().hasHeightForWidth());
        welkom_inlog_button->setSizePolicy(sizePolicy);
        welkom_inlog_button->setFont(font1);
        welkom_logo = new QLabel(welkomScherm);
        welkom_logo->setObjectName(QString::fromUtf8("welkom_logo"));
        welkom_logo->setGeometry(QRect(30, 20, 211, 201));
        welkom_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        welkom_logo->setScaledContents(true);
        welkom_taal_label = new QLabel(welkomScherm);
        welkom_taal_label->setObjectName(QString::fromUtf8("welkom_taal_label"));
        welkom_taal_label->setGeometry(QRect(1170, 65, 41, 51));
        QFont font3;
        font3.setPointSize(20);
        welkom_taal_label->setFont(font3);
        welkom_taal_label->setFrameShape(QFrame::Box);
        welkom_taal_label->setFrameShadow(QFrame::Plain);
        welkom_taal_label->setLineWidth(2);
        ATM->addWidget(welkomScherm);
        inlogScherm = new QWidget();
        inlogScherm->setObjectName(QString::fromUtf8("inlogScherm"));
        inlog_voerpin_label = new QLabel(inlogScherm);
        inlog_voerpin_label->setObjectName(QString::fromUtf8("inlog_voerpin_label"));
        inlog_voerpin_label->setGeometry(QRect(540, 290, 201, 31));
        QFont font4;
        font4.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font4.setPointSize(18);
        inlog_voerpin_label->setFont(font4);
        inlog_voerpin_label->setCursor(QCursor(Qt::ArrowCursor));
        inlog_taal_button = new QPushButton(inlogScherm);
        inlog_taal_button->setObjectName(QString::fromUtf8("inlog_taal_button"));
        inlog_taal_button->setGeometry(QRect(950, 40, 201, 101));
        sizePolicy.setHeightForWidth(inlog_taal_button->sizePolicy().hasHeightForWidth());
        inlog_taal_button->setSizePolicy(sizePolicy);
        QFont font5;
        font5.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font5.setPointSize(14);
        inlog_taal_button->setFont(font5);
        inlog_hoofd_button = new QPushButton(inlogScherm);
        inlog_hoofd_button->setObjectName(QString::fromUtf8("inlog_hoofd_button"));
        inlog_hoofd_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(inlog_hoofd_button->sizePolicy().hasHeightForWidth());
        inlog_hoofd_button->setSizePolicy(sizePolicy);
        inlog_hoofd_button->setFont(font1);
        inlog_welkom_button = new QPushButton(inlogScherm);
        inlog_welkom_button->setObjectName(QString::fromUtf8("inlog_welkom_button"));
        inlog_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(inlog_welkom_button->sizePolicy().hasHeightForWidth());
        inlog_welkom_button->setSizePolicy(sizePolicy);
        inlog_welkom_button->setFont(font1);
        inlog_label = new QLabel(inlogScherm);
        inlog_label->setObjectName(QString::fromUtf8("inlog_label"));
        inlog_label->setGeometry(QRect(450, 390, 381, 31));
        inlog_label->setFont(font4);
        inlog_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        inlog_invoerveldPincode = new QLineEdit(inlogScherm);
        inlog_invoerveldPincode->setObjectName(QString::fromUtf8("inlog_invoerveldPincode"));
        inlog_invoerveldPincode->setGeometry(QRect(540, 330, 200, 51));
        inlog_invoerveldPincode->setFont(font3);
        inlog_invoerveldPincode->setEchoMode(QLineEdit::Password);
        inlog_logo = new QLabel(inlogScherm);
        inlog_logo->setObjectName(QString::fromUtf8("inlog_logo"));
        inlog_logo->setGeometry(QRect(30, 20, 211, 201));
        inlog_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        inlog_logo->setScaledContents(true);
        inlog_delete = new QLabel(inlogScherm);
        inlog_delete->setObjectName(QString::fromUtf8("inlog_delete"));
        inlog_delete->setGeometry(QRect(980, 460, 171, 101));
        QFont font6;
        font6.setPointSize(3);
        inlog_delete->setFont(font6);
        inlog_delete->setPixmap(QPixmap(QString::fromUtf8("Afbeelding1.png")));
        inlog_delete->setScaledContents(true);
        inlog_taal_label = new QLabel(inlogScherm);
        inlog_taal_label->setObjectName(QString::fromUtf8("inlog_taal_label"));
        inlog_taal_label->setGeometry(QRect(1170, 65, 41, 51));
        inlog_taal_label->setFont(font3);
        inlog_taal_label->setFrameShape(QFrame::Box);
        inlog_taal_label->setFrameShadow(QFrame::Plain);
        inlog_taal_label->setLineWidth(2);
        inlog_delete_label = new QLabel(inlogScherm);
        inlog_delete_label->setObjectName(QString::fromUtf8("inlog_delete_label"));
        inlog_delete_label->setGeometry(QRect(1170, 485, 41, 51));
        inlog_delete_label->setFont(font3);
        inlog_delete_label->setFrameShape(QFrame::Box);
        inlog_delete_label->setFrameShadow(QFrame::Plain);
        inlog_delete_label->setLineWidth(2);
        inlog_hoofd_label = new QLabel(inlogScherm);
        inlog_hoofd_label->setObjectName(QString::fromUtf8("inlog_hoofd_label"));
        inlog_hoofd_label->setGeometry(QRect(1170, 620, 41, 51));
        inlog_hoofd_label->setFont(font3);
        inlog_hoofd_label->setFrameShape(QFrame::Box);
        inlog_hoofd_label->setFrameShadow(QFrame::Plain);
        inlog_hoofd_label->setLineWidth(2);
        inlog_welkom_label = new QLabel(inlogScherm);
        inlog_welkom_label->setObjectName(QString::fromUtf8("inlog_welkom_label"));
        inlog_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        inlog_welkom_label->setFont(font3);
        inlog_welkom_label->setFrameShape(QFrame::Box);
        inlog_welkom_label->setFrameShadow(QFrame::Plain);
        inlog_welkom_label->setLineWidth(2);
        ATM->addWidget(inlogScherm);
        taalScherm = new QWidget();
        taalScherm->setObjectName(QString::fromUtf8("taalScherm"));
        taalScherm->setEnabled(true);
        taal_optieNederlands_button = new QPushButton(taalScherm);
        taal_optieNederlands_button->setObjectName(QString::fromUtf8("taal_optieNederlands_button"));
        taal_optieNederlands_button->setGeometry(QRect(870, 50, 171, 61));
        sizePolicy.setHeightForWidth(taal_optieNederlands_button->sizePolicy().hasHeightForWidth());
        taal_optieNederlands_button->setSizePolicy(sizePolicy);
        taal_optieNederlands_button->setFont(font5);
        taal_optieEngels_button = new QPushButton(taalScherm);
        taal_optieEngels_button->setObjectName(QString::fromUtf8("taal_optieEngels_button"));
        taal_optieEngels_button->setGeometry(QRect(870, 280, 171, 61));
        sizePolicy.setHeightForWidth(taal_optieEngels_button->sizePolicy().hasHeightForWidth());
        taal_optieEngels_button->setSizePolicy(sizePolicy);
        taal_optieEngels_button->setFont(font5);
        taal_optieDuits_button = new QPushButton(taalScherm);
        taal_optieDuits_button->setObjectName(QString::fromUtf8("taal_optieDuits_button"));
        taal_optieDuits_button->setGeometry(QRect(870, 170, 171, 61));
        taal_optieDuits_button->setFont(font5);
        taal_welkom_button = new QPushButton(taalScherm);
        taal_welkom_button->setObjectName(QString::fromUtf8("taal_welkom_button"));
        taal_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(taal_welkom_button->sizePolicy().hasHeightForWidth());
        taal_welkom_button->setSizePolicy(sizePolicy);
        taal_welkom_button->setFont(font5);
        taal_hoofd_of_welkom_of_inlog_button = new QPushButton(taalScherm);
        taal_hoofd_of_welkom_of_inlog_button->setObjectName(QString::fromUtf8("taal_hoofd_of_welkom_of_inlog_button"));
        taal_hoofd_of_welkom_of_inlog_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(taal_hoofd_of_welkom_of_inlog_button->sizePolicy().hasHeightForWidth());
        taal_hoofd_of_welkom_of_inlog_button->setSizePolicy(sizePolicy);
        taal_hoofd_of_welkom_of_inlog_button->setFont(font5);
        taal_duitsland_vlag = new QLabel(taalScherm);
        taal_duitsland_vlag->setObjectName(QString::fromUtf8("taal_duitsland_vlag"));
        taal_duitsland_vlag->setGeometry(QRect(1060, 140, 111, 111));
        taal_duitsland_vlag->setPixmap(QPixmap(QString::fromUtf8("duitsland_100.png")));
        taal_duitsland_vlag->setScaledContents(true);
        taal_engeland_vlag = new QLabel(taalScherm);
        taal_engeland_vlag->setObjectName(QString::fromUtf8("taal_engeland_vlag"));
        taal_engeland_vlag->setGeometry(QRect(1060, 260, 111, 111));
        taal_engeland_vlag->setPixmap(QPixmap(QString::fromUtf8("engeland_100.png")));
        taal_engeland_vlag->setScaledContents(true);
        taal_nederland_vlag = new QLabel(taalScherm);
        taal_nederland_vlag->setObjectName(QString::fromUtf8("taal_nederland_vlag"));
        taal_nederland_vlag->setGeometry(QRect(1060, 20, 111, 111));
        taal_nederland_vlag->setPixmap(QPixmap(QString::fromUtf8("nederland_100.png")));
        taal_nederland_vlag->setScaledContents(true);
        taal_label = new QLabel(taalScherm);
        taal_label->setObjectName(QString::fromUtf8("taal_label"));
        taal_label->setGeometry(QRect(500, 290, 281, 101));
        QFont font7;
        font7.setPointSize(18);
        taal_label->setFont(font7);
        taal_logo = new QLabel(taalScherm);
        taal_logo->setObjectName(QString::fromUtf8("taal_logo"));
        taal_logo->setGeometry(QRect(30, 20, 211, 201));
        taal_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        taal_logo->setScaledContents(true);
        taal_nederlands_label = new QLabel(taalScherm);
        taal_nederlands_label->setObjectName(QString::fromUtf8("taal_nederlands_label"));
        taal_nederlands_label->setGeometry(QRect(1190, 50, 41, 51));
        taal_nederlands_label->setFont(font3);
        taal_nederlands_label->setFrameShape(QFrame::Box);
        taal_nederlands_label->setFrameShadow(QFrame::Plain);
        taal_nederlands_label->setLineWidth(2);
        taal_duitsland_label = new QLabel(taalScherm);
        taal_duitsland_label->setObjectName(QString::fromUtf8("taal_duitsland_label"));
        taal_duitsland_label->setGeometry(QRect(1190, 170, 41, 51));
        taal_duitsland_label->setFont(font3);
        taal_duitsland_label->setFrameShape(QFrame::Box);
        taal_duitsland_label->setFrameShadow(QFrame::Plain);
        taal_duitsland_label->setLineWidth(2);
        taal_engeland_label = new QLabel(taalScherm);
        taal_engeland_label->setObjectName(QString::fromUtf8("taal_engeland_label"));
        taal_engeland_label->setGeometry(QRect(1190, 290, 41, 51));
        taal_engeland_label->setFont(font3);
        taal_engeland_label->setFrameShape(QFrame::Box);
        taal_engeland_label->setFrameShadow(QFrame::Plain);
        taal_engeland_label->setLineWidth(2);
        taal_back_label = new QLabel(taalScherm);
        taal_back_label->setObjectName(QString::fromUtf8("taal_back_label"));
        taal_back_label->setGeometry(QRect(1170, 620, 41, 51));
        taal_back_label->setFont(font3);
        taal_back_label->setFrameShape(QFrame::Box);
        taal_back_label->setFrameShadow(QFrame::Plain);
        taal_back_label->setLineWidth(2);
        taal_welkom_label = new QLabel(taalScherm);
        taal_welkom_label->setObjectName(QString::fromUtf8("taal_welkom_label"));
        taal_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        taal_welkom_label->setFont(font3);
        taal_welkom_label->setFrameShape(QFrame::Box);
        taal_welkom_label->setFrameShadow(QFrame::Plain);
        taal_welkom_label->setLineWidth(2);
        ATM->addWidget(taalScherm);
        hoofdScherm = new QWidget();
        hoofdScherm->setObjectName(QString::fromUtf8("hoofdScherm"));
        hoofdLabel = new QLabel(hoofdScherm);
        hoofdLabel->setObjectName(QString::fromUtf8("hoofdLabel"));
        hoofdLabel->setGeometry(QRect(510, 280, 231, 131));
        hoofdLabel->setFont(font5);
        hoofd_snelPinnen_button = new QPushButton(hoofdScherm);
        hoofd_snelPinnen_button->setObjectName(QString::fromUtf8("hoofd_snelPinnen_button"));
        hoofd_snelPinnen_button->setGeometry(QRect(880, 300, 271, 131));
        sizePolicy.setHeightForWidth(hoofd_snelPinnen_button->sizePolicy().hasHeightForWidth());
        hoofd_snelPinnen_button->setSizePolicy(sizePolicy);
        hoofd_snelPinnen_button->setFont(font5);
        hoofd_saldo_button = new QPushButton(hoofdScherm);
        hoofd_saldo_button->setObjectName(QString::fromUtf8("hoofd_saldo_button"));
        hoofd_saldo_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(hoofd_saldo_button->sizePolicy().hasHeightForWidth());
        hoofd_saldo_button->setSizePolicy(sizePolicy);
        hoofd_saldo_button->setFont(font5);
        hoofd_pinKeuze_button = new QPushButton(hoofdScherm);
        hoofd_pinKeuze_button->setObjectName(QString::fromUtf8("hoofd_pinKeuze_button"));
        hoofd_pinKeuze_button->setGeometry(QRect(880, 440, 271, 131));
        sizePolicy.setHeightForWidth(hoofd_pinKeuze_button->sizePolicy().hasHeightForWidth());
        hoofd_pinKeuze_button->setSizePolicy(sizePolicy);
        hoofd_pinKeuze_button->setFont(font5);
        hoofd_taal_button = new QPushButton(hoofdScherm);
        hoofd_taal_button->setObjectName(QString::fromUtf8("hoofd_taal_button"));
        hoofd_taal_button->setGeometry(QRect(950, 40, 201, 101));
        sizePolicy.setHeightForWidth(hoofd_taal_button->sizePolicy().hasHeightForWidth());
        hoofd_taal_button->setSizePolicy(sizePolicy);
        hoofd_taal_button->setFont(font5);
        hoofd_welkom_button = new QPushButton(hoofdScherm);
        hoofd_welkom_button->setObjectName(QString::fromUtf8("hoofd_welkom_button"));
        hoofd_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(hoofd_welkom_button->sizePolicy().hasHeightForWidth());
        hoofd_welkom_button->setSizePolicy(sizePolicy);
        hoofd_welkom_button->setFont(font5);
        hoofd_logo = new QLabel(hoofdScherm);
        hoofd_logo->setObjectName(QString::fromUtf8("hoofd_logo"));
        hoofd_logo->setGeometry(QRect(30, 20, 211, 201));
        hoofd_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        hoofd_logo->setScaledContents(true);
        hoofd_taal_label = new QLabel(hoofdScherm);
        hoofd_taal_label->setObjectName(QString::fromUtf8("hoofd_taal_label"));
        hoofd_taal_label->setGeometry(QRect(1170, 65, 41, 51));
        hoofd_taal_label->setFont(font3);
        hoofd_taal_label->setFrameShape(QFrame::Box);
        hoofd_taal_label->setFrameShadow(QFrame::Plain);
        hoofd_taal_label->setLineWidth(2);
        hoofd_snelPinnen_label = new QLabel(hoofdScherm);
        hoofd_snelPinnen_label->setObjectName(QString::fromUtf8("hoofd_snelPinnen_label"));
        hoofd_snelPinnen_label->setGeometry(QRect(1170, 340, 41, 51));
        hoofd_snelPinnen_label->setFont(font3);
        hoofd_snelPinnen_label->setFrameShape(QFrame::Box);
        hoofd_snelPinnen_label->setFrameShadow(QFrame::Plain);
        hoofd_snelPinnen_label->setLineWidth(2);
        hoofd_pinKeuze_label = new QLabel(hoofdScherm);
        hoofd_pinKeuze_label->setObjectName(QString::fromUtf8("hoofd_pinKeuze_label"));
        hoofd_pinKeuze_label->setGeometry(QRect(1170, 480, 41, 51));
        hoofd_pinKeuze_label->setFont(font3);
        hoofd_pinKeuze_label->setFrameShape(QFrame::Box);
        hoofd_pinKeuze_label->setFrameShadow(QFrame::Plain);
        hoofd_pinKeuze_label->setLineWidth(2);
        hoofd_saldo_label = new QLabel(hoofdScherm);
        hoofd_saldo_label->setObjectName(QString::fromUtf8("hoofd_saldo_label"));
        hoofd_saldo_label->setGeometry(QRect(1170, 620, 41, 51));
        hoofd_saldo_label->setFont(font3);
        hoofd_saldo_label->setFrameShape(QFrame::Box);
        hoofd_saldo_label->setFrameShadow(QFrame::Plain);
        hoofd_saldo_label->setLineWidth(2);
        hoofd_welkom_label = new QLabel(hoofdScherm);
        hoofd_welkom_label->setObjectName(QString::fromUtf8("hoofd_welkom_label"));
        hoofd_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        hoofd_welkom_label->setFont(font3);
        hoofd_welkom_label->setFrameShape(QFrame::Box);
        hoofd_welkom_label->setFrameShadow(QFrame::Plain);
        hoofd_welkom_label->setLineWidth(2);
        ATM->addWidget(hoofdScherm);
        saldoScherm = new QWidget();
        saldoScherm->setObjectName(QString::fromUtf8("saldoScherm"));
        saldo_label_wat_is_saldo = new QLabel(saldoScherm);
        saldo_label_wat_is_saldo->setObjectName(QString::fromUtf8("saldo_label_wat_is_saldo"));
        saldo_label_wat_is_saldo->setGeometry(QRect(550, 300, 151, 61));
        saldo_label_wat_is_saldo->setFont(font4);
        saldo_pinKeuze_button = new QPushButton(saldoScherm);
        saldo_pinKeuze_button->setObjectName(QString::fromUtf8("saldo_pinKeuze_button"));
        saldo_pinKeuze_button->setGeometry(QRect(880, 440, 271, 131));
        sizePolicy.setHeightForWidth(saldo_pinKeuze_button->sizePolicy().hasHeightForWidth());
        saldo_pinKeuze_button->setSizePolicy(sizePolicy);
        saldo_pinKeuze_button->setFont(font5);
        saldo_welkom_button = new QPushButton(saldoScherm);
        saldo_welkom_button->setObjectName(QString::fromUtf8("saldo_welkom_button"));
        saldo_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(saldo_welkom_button->sizePolicy().hasHeightForWidth());
        saldo_welkom_button->setSizePolicy(sizePolicy);
        saldo_welkom_button->setFont(font5);
        saldo_hoofdscherm_button = new QPushButton(saldoScherm);
        saldo_hoofdscherm_button->setObjectName(QString::fromUtf8("saldo_hoofdscherm_button"));
        saldo_hoofdscherm_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(saldo_hoofdscherm_button->sizePolicy().hasHeightForWidth());
        saldo_hoofdscherm_button->setSizePolicy(sizePolicy);
        saldo_hoofdscherm_button->setFont(font5);
        saldo_label = new QLabel(saldoScherm);
        saldo_label->setObjectName(QString::fromUtf8("saldo_label"));
        saldo_label->setGeometry(QRect(570, 370, 101, 71));
        saldo_label->setFont(font4);
        saldo_logo = new QLabel(saldoScherm);
        saldo_logo->setObjectName(QString::fromUtf8("saldo_logo"));
        saldo_logo->setGeometry(QRect(30, 20, 211, 201));
        saldo_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        saldo_logo->setScaledContents(true);
        saldo_pinKeuze_label = new QLabel(saldoScherm);
        saldo_pinKeuze_label->setObjectName(QString::fromUtf8("saldo_pinKeuze_label"));
        saldo_pinKeuze_label->setGeometry(QRect(1170, 480, 41, 51));
        saldo_pinKeuze_label->setFont(font3);
        saldo_pinKeuze_label->setFrameShape(QFrame::Box);
        saldo_pinKeuze_label->setFrameShadow(QFrame::Plain);
        saldo_pinKeuze_label->setLineWidth(2);
        saldo_hoofdscherm_label = new QLabel(saldoScherm);
        saldo_hoofdscherm_label->setObjectName(QString::fromUtf8("saldo_hoofdscherm_label"));
        saldo_hoofdscherm_label->setGeometry(QRect(1170, 620, 41, 51));
        saldo_hoofdscherm_label->setFont(font3);
        saldo_hoofdscherm_label->setFrameShape(QFrame::Box);
        saldo_hoofdscherm_label->setFrameShadow(QFrame::Plain);
        saldo_hoofdscherm_label->setLineWidth(2);
        saldo_welkom_label = new QLabel(saldoScherm);
        saldo_welkom_label->setObjectName(QString::fromUtf8("saldo_welkom_label"));
        saldo_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        saldo_welkom_label->setFont(font3);
        saldo_welkom_label->setFrameShape(QFrame::Box);
        saldo_welkom_label->setFrameShadow(QFrame::Plain);
        saldo_welkom_label->setLineWidth(2);
        ATM->addWidget(saldoScherm);
        pinKeuzeScherm = new QWidget();
        pinKeuzeScherm->setObjectName(QString::fromUtf8("pinKeuzeScherm"));
        pinKeuze_label = new QLabel(pinKeuzeScherm);
        pinKeuze_label->setObjectName(QString::fromUtf8("pinKeuze_label"));
        pinKeuze_label->setGeometry(QRect(470, 340, 301, 41));
        pinKeuze_label->setFont(font4);
        pinKeuze_optie1_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_optie1_button->setObjectName(QString::fromUtf8("pinKeuze_optie1_button"));
        pinKeuze_optie1_button->setGeometry(QRect(880, 440, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_optie1_button->sizePolicy().hasHeightForWidth());
        pinKeuze_optie1_button->setSizePolicy(sizePolicy);
        pinKeuze_optie1_button->setFont(font5);
        pinKeuze_optie2_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_optie2_button->setObjectName(QString::fromUtf8("pinKeuze_optie2_button"));
        pinKeuze_optie2_button->setGeometry(QRect(880, 300, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_optie2_button->sizePolicy().hasHeightForWidth());
        pinKeuze_optie2_button->setSizePolicy(sizePolicy);
        pinKeuze_optie2_button->setFont(font5);
        pinKeuze_optie3_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_optie3_button->setObjectName(QString::fromUtf8("pinKeuze_optie3_button"));
        pinKeuze_optie3_button->setGeometry(QRect(880, 160, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_optie3_button->sizePolicy().hasHeightForWidth());
        pinKeuze_optie3_button->setSizePolicy(sizePolicy);
        pinKeuze_optie3_button->setFont(font5);
        pinKeuze_optie4_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_optie4_button->setObjectName(QString::fromUtf8("pinKeuze_optie4_button"));
        pinKeuze_optie4_button->setGeometry(QRect(880, 20, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_optie4_button->sizePolicy().hasHeightForWidth());
        pinKeuze_optie4_button->setSizePolicy(sizePolicy);
        pinKeuze_optie4_button->setFont(font5);
        pinKeuze_optie5_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_optie5_button->setObjectName(QString::fromUtf8("pinKeuze_optie5_button"));
        pinKeuze_optie5_button->setGeometry(QRect(100, 300, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_optie5_button->sizePolicy().hasHeightForWidth());
        pinKeuze_optie5_button->setSizePolicy(sizePolicy);
        pinKeuze_optie5_button->setFont(font5);
        pinKeuze_zelfBedragKiezen_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_zelfBedragKiezen_button->setObjectName(QString::fromUtf8("pinKeuze_zelfBedragKiezen_button"));
        pinKeuze_zelfBedragKiezen_button->setGeometry(QRect(100, 440, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_zelfBedragKiezen_button->sizePolicy().hasHeightForWidth());
        pinKeuze_zelfBedragKiezen_button->setSizePolicy(sizePolicy);
        pinKeuze_zelfBedragKiezen_button->setFont(font5);
        pinKeuze_welkom_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_welkom_button->setObjectName(QString::fromUtf8("pinKeuze_welkom_button"));
        pinKeuze_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_welkom_button->sizePolicy().hasHeightForWidth());
        pinKeuze_welkom_button->setSizePolicy(sizePolicy);
        pinKeuze_welkom_button->setFont(font5);
        pinKeuze_hoofd_button = new QPushButton(pinKeuzeScherm);
        pinKeuze_hoofd_button->setObjectName(QString::fromUtf8("pinKeuze_hoofd_button"));
        pinKeuze_hoofd_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(pinKeuze_hoofd_button->sizePolicy().hasHeightForWidth());
        pinKeuze_hoofd_button->setSizePolicy(sizePolicy);
        pinKeuze_hoofd_button->setFont(font5);
        pinKeuze_logo = new QLabel(pinKeuzeScherm);
        pinKeuze_logo->setObjectName(QString::fromUtf8("pinKeuze_logo"));
        pinKeuze_logo->setGeometry(QRect(30, 20, 211, 201));
        pinKeuze_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        pinKeuze_logo->setScaledContents(true);
        pinKeuze_optie4_label = new QLabel(pinKeuzeScherm);
        pinKeuze_optie4_label->setObjectName(QString::fromUtf8("pinKeuze_optie4_label"));
        pinKeuze_optie4_label->setGeometry(QRect(1170, 60, 41, 51));
        pinKeuze_optie4_label->setFont(font3);
        pinKeuze_optie4_label->setFrameShape(QFrame::Box);
        pinKeuze_optie4_label->setFrameShadow(QFrame::Plain);
        pinKeuze_optie4_label->setLineWidth(2);
        pinKeuze_optie3_label = new QLabel(pinKeuzeScherm);
        pinKeuze_optie3_label->setObjectName(QString::fromUtf8("pinKeuze_optie3_label"));
        pinKeuze_optie3_label->setGeometry(QRect(1170, 200, 41, 51));
        pinKeuze_optie3_label->setFont(font3);
        pinKeuze_optie3_label->setFrameShape(QFrame::Box);
        pinKeuze_optie3_label->setFrameShadow(QFrame::Plain);
        pinKeuze_optie3_label->setLineWidth(2);
        pinKeuze_optie2_label = new QLabel(pinKeuzeScherm);
        pinKeuze_optie2_label->setObjectName(QString::fromUtf8("pinKeuze_optie2_label"));
        pinKeuze_optie2_label->setGeometry(QRect(1170, 340, 41, 51));
        pinKeuze_optie2_label->setFont(font3);
        pinKeuze_optie2_label->setFrameShape(QFrame::Box);
        pinKeuze_optie2_label->setFrameShadow(QFrame::Plain);
        pinKeuze_optie2_label->setLineWidth(2);
        pinKeuze_optie1_label = new QLabel(pinKeuzeScherm);
        pinKeuze_optie1_label->setObjectName(QString::fromUtf8("pinKeuze_optie1_label"));
        pinKeuze_optie1_label->setGeometry(QRect(1170, 480, 41, 51));
        pinKeuze_optie1_label->setFont(font3);
        pinKeuze_optie1_label->setFrameShape(QFrame::Box);
        pinKeuze_optie1_label->setFrameShadow(QFrame::Plain);
        pinKeuze_optie1_label->setLineWidth(2);
        pinKeuze_hoofd_label = new QLabel(pinKeuzeScherm);
        pinKeuze_hoofd_label->setObjectName(QString::fromUtf8("pinKeuze_hoofd_label"));
        pinKeuze_hoofd_label->setGeometry(QRect(1170, 620, 41, 51));
        pinKeuze_hoofd_label->setFont(font3);
        pinKeuze_hoofd_label->setFrameShape(QFrame::Box);
        pinKeuze_hoofd_label->setFrameShadow(QFrame::Plain);
        pinKeuze_hoofd_label->setLineWidth(2);
        pinKeuze_optie5_label = new QLabel(pinKeuzeScherm);
        pinKeuze_optie5_label->setObjectName(QString::fromUtf8("pinKeuze_optie5_label"));
        pinKeuze_optie5_label->setGeometry(QRect(40, 340, 41, 51));
        pinKeuze_optie5_label->setFont(font3);
        pinKeuze_optie5_label->setFrameShape(QFrame::Box);
        pinKeuze_optie5_label->setFrameShadow(QFrame::Plain);
        pinKeuze_optie5_label->setLineWidth(2);
        pinKeuze_zelfBedragKiezen_label = new QLabel(pinKeuzeScherm);
        pinKeuze_zelfBedragKiezen_label->setObjectName(QString::fromUtf8("pinKeuze_zelfBedragKiezen_label"));
        pinKeuze_zelfBedragKiezen_label->setGeometry(QRect(40, 480, 41, 51));
        pinKeuze_zelfBedragKiezen_label->setFont(font3);
        pinKeuze_zelfBedragKiezen_label->setFrameShape(QFrame::Box);
        pinKeuze_zelfBedragKiezen_label->setFrameShadow(QFrame::Plain);
        pinKeuze_zelfBedragKiezen_label->setLineWidth(2);
        pinKeuze_welkom_label = new QLabel(pinKeuzeScherm);
        pinKeuze_welkom_label->setObjectName(QString::fromUtf8("pinKeuze_welkom_label"));
        pinKeuze_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        pinKeuze_welkom_label->setFont(font3);
        pinKeuze_welkom_label->setFrameShape(QFrame::Box);
        pinKeuze_welkom_label->setFrameShadow(QFrame::Plain);
        pinKeuze_welkom_label->setLineWidth(2);
        ATM->addWidget(pinKeuzeScherm);
        biljetScherm = new QWidget();
        biljetScherm->setObjectName(QString::fromUtf8("biljetScherm"));
        biljetKeuze_label = new QLabel(biljetScherm);
        biljetKeuze_label->setObjectName(QString::fromUtf8("biljetKeuze_label"));
        biljetKeuze_label->setGeometry(QRect(510, 320, 251, 71));
        biljetKeuze_label->setFont(font4);
        biljetKeuze_welkom_button = new QPushButton(biljetScherm);
        biljetKeuze_welkom_button->setObjectName(QString::fromUtf8("biljetKeuze_welkom_button"));
        biljetKeuze_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(biljetKeuze_welkom_button->sizePolicy().hasHeightForWidth());
        biljetKeuze_welkom_button->setSizePolicy(sizePolicy);
        biljetKeuze_welkom_button->setFont(font5);
        biljetKeuze_hoofd_button = new QPushButton(biljetScherm);
        biljetKeuze_hoofd_button->setObjectName(QString::fromUtf8("biljetKeuze_hoofd_button"));
        biljetKeuze_hoofd_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(biljetKeuze_hoofd_button->sizePolicy().hasHeightForWidth());
        biljetKeuze_hoofd_button->setSizePolicy(sizePolicy);
        biljetKeuze_hoofd_button->setFont(font5);
        biljetKeuze_biljetNietBelangrijk_button = new QPushButton(biljetScherm);
        biljetKeuze_biljetNietBelangrijk_button->setObjectName(QString::fromUtf8("biljetKeuze_biljetNietBelangrijk_button"));
        biljetKeuze_biljetNietBelangrijk_button->setGeometry(QRect(880, 440, 271, 131));
        sizePolicy.setHeightForWidth(biljetKeuze_biljetNietBelangrijk_button->sizePolicy().hasHeightForWidth());
        biljetKeuze_biljetNietBelangrijk_button->setSizePolicy(sizePolicy);
        biljetKeuze_biljetNietBelangrijk_button->setFont(font5);
        biljetKeuze_biljetOpties1_button = new QPushButton(biljetScherm);
        biljetKeuze_biljetOpties1_button->setObjectName(QString::fromUtf8("biljetKeuze_biljetOpties1_button"));
        biljetKeuze_biljetOpties1_button->setGeometry(QRect(880, 300, 271, 131));
        sizePolicy.setHeightForWidth(biljetKeuze_biljetOpties1_button->sizePolicy().hasHeightForWidth());
        biljetKeuze_biljetOpties1_button->setSizePolicy(sizePolicy);
        biljetKeuze_biljetOpties1_button->setFont(font5);
        biljetKeuze_logo = new QLabel(biljetScherm);
        biljetKeuze_logo->setObjectName(QString::fromUtf8("biljetKeuze_logo"));
        biljetKeuze_logo->setGeometry(QRect(30, 20, 211, 201));
        biljetKeuze_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        biljetKeuze_logo->setScaledContents(true);
        biljetKeuze_hoofd_label = new QLabel(biljetScherm);
        biljetKeuze_hoofd_label->setObjectName(QString::fromUtf8("biljetKeuze_hoofd_label"));
        biljetKeuze_hoofd_label->setGeometry(QRect(1170, 620, 41, 51));
        biljetKeuze_hoofd_label->setFont(font3);
        biljetKeuze_hoofd_label->setFrameShape(QFrame::Box);
        biljetKeuze_hoofd_label->setFrameShadow(QFrame::Plain);
        biljetKeuze_hoofd_label->setLineWidth(2);
        biljetKeuze_biljetNietBelangrijk_label = new QLabel(biljetScherm);
        biljetKeuze_biljetNietBelangrijk_label->setObjectName(QString::fromUtf8("biljetKeuze_biljetNietBelangrijk_label"));
        biljetKeuze_biljetNietBelangrijk_label->setGeometry(QRect(1170, 480, 41, 51));
        biljetKeuze_biljetNietBelangrijk_label->setFont(font3);
        biljetKeuze_biljetNietBelangrijk_label->setFrameShape(QFrame::Box);
        biljetKeuze_biljetNietBelangrijk_label->setFrameShadow(QFrame::Plain);
        biljetKeuze_biljetNietBelangrijk_label->setLineWidth(2);
        biljetKeuze_biljetOpties1_label = new QLabel(biljetScherm);
        biljetKeuze_biljetOpties1_label->setObjectName(QString::fromUtf8("biljetKeuze_biljetOpties1_label"));
        biljetKeuze_biljetOpties1_label->setGeometry(QRect(1170, 330, 41, 51));
        biljetKeuze_biljetOpties1_label->setFont(font3);
        biljetKeuze_biljetOpties1_label->setFrameShape(QFrame::Box);
        biljetKeuze_biljetOpties1_label->setFrameShadow(QFrame::Plain);
        biljetKeuze_biljetOpties1_label->setLineWidth(2);
        biljetKeuze_welkom_label = new QLabel(biljetScherm);
        biljetKeuze_welkom_label->setObjectName(QString::fromUtf8("biljetKeuze_welkom_label"));
        biljetKeuze_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        biljetKeuze_welkom_label->setFont(font3);
        biljetKeuze_welkom_label->setFrameShape(QFrame::Box);
        biljetKeuze_welkom_label->setFrameShadow(QFrame::Plain);
        biljetKeuze_welkom_label->setLineWidth(2);
        ATM->addWidget(biljetScherm);
        bedragScherm = new QWidget();
        bedragScherm->setObjectName(QString::fromUtf8("bedragScherm"));
        bedrag_label = new QLabel(bedragScherm);
        bedrag_label->setObjectName(QString::fromUtf8("bedrag_label"));
        bedrag_label->setGeometry(QRect(490, 250, 271, 51));
        bedrag_label->setFont(font4);
        bedragKeuze_hoofd_button = new QPushButton(bedragScherm);
        bedragKeuze_hoofd_button->setObjectName(QString::fromUtf8("bedragKeuze_hoofd_button"));
        bedragKeuze_hoofd_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(bedragKeuze_hoofd_button->sizePolicy().hasHeightForWidth());
        bedragKeuze_hoofd_button->setSizePolicy(sizePolicy);
        bedragKeuze_hoofd_button->setFont(font5);
        bedragKeuze_welkom_button = new QPushButton(bedragScherm);
        bedragKeuze_welkom_button->setObjectName(QString::fromUtf8("bedragKeuze_welkom_button"));
        bedragKeuze_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(bedragKeuze_welkom_button->sizePolicy().hasHeightForWidth());
        bedragKeuze_welkom_button->setSizePolicy(sizePolicy);
        bedragKeuze_welkom_button->setFont(font5);
        bedragKeuze_bevestigen_button = new QPushButton(bedragScherm);
        bedragKeuze_bevestigen_button->setObjectName(QString::fromUtf8("bedragKeuze_bevestigen_button"));
        bedragKeuze_bevestigen_button->setGeometry(QRect(880, 440, 271, 131));
        sizePolicy.setHeightForWidth(bedragKeuze_bevestigen_button->sizePolicy().hasHeightForWidth());
        bedragKeuze_bevestigen_button->setSizePolicy(sizePolicy);
        bedragKeuze_bevestigen_button->setFont(font5);
        bedragKeuze_invoerVeld = new QLineEdit(bedragScherm);
        bedragKeuze_invoerVeld->setObjectName(QString::fromUtf8("bedragKeuze_invoerVeld"));
        bedragKeuze_invoerVeld->setGeometry(QRect(540, 320, 181, 51));
        bedragKeuze_invoerVeld->setFont(font4);
        bedragKeuze_error_label = new QLabel(bedragScherm);
        bedragKeuze_error_label->setObjectName(QString::fromUtf8("bedragKeuze_error_label"));
        bedragKeuze_error_label->setGeometry(QRect(420, 390, 421, 61));
        bedragKeuze_error_label->setFont(font4);
        bedragKeuze_error_label->setAlignment(Qt::AlignCenter);
        bedragKeuze_error_label->setWordWrap(true);
        bedragKeuze_logo = new QLabel(bedragScherm);
        bedragKeuze_logo->setObjectName(QString::fromUtf8("bedragKeuze_logo"));
        bedragKeuze_logo->setGeometry(QRect(30, 20, 211, 201));
        bedragKeuze_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        bedragKeuze_logo->setScaledContents(true);
        bedragKeuze_bevestigen_label = new QLabel(bedragScherm);
        bedragKeuze_bevestigen_label->setObjectName(QString::fromUtf8("bedragKeuze_bevestigen_label"));
        bedragKeuze_bevestigen_label->setGeometry(QRect(1170, 480, 41, 51));
        bedragKeuze_bevestigen_label->setFont(font3);
        bedragKeuze_bevestigen_label->setFrameShape(QFrame::Box);
        bedragKeuze_bevestigen_label->setFrameShadow(QFrame::Plain);
        bedragKeuze_bevestigen_label->setLineWidth(2);
        bedragKeuze_hoofd_label = new QLabel(bedragScherm);
        bedragKeuze_hoofd_label->setObjectName(QString::fromUtf8("bedragKeuze_hoofd_label"));
        bedragKeuze_hoofd_label->setGeometry(QRect(1170, 620, 41, 51));
        bedragKeuze_hoofd_label->setFont(font3);
        bedragKeuze_hoofd_label->setFrameShape(QFrame::Box);
        bedragKeuze_hoofd_label->setFrameShadow(QFrame::Plain);
        bedragKeuze_hoofd_label->setLineWidth(2);
        bedragKeuze_welkom_label = new QLabel(bedragScherm);
        bedragKeuze_welkom_label->setObjectName(QString::fromUtf8("bedragKeuze_welkom_label"));
        bedragKeuze_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        bedragKeuze_welkom_label->setFont(font3);
        bedragKeuze_welkom_label->setFrameShape(QFrame::Box);
        bedragKeuze_welkom_label->setFrameShadow(QFrame::Plain);
        bedragKeuze_welkom_label->setLineWidth(2);
        ATM->addWidget(bedragScherm);
        bonScherm = new QWidget();
        bonScherm->setObjectName(QString::fromUtf8("bonScherm"));
        bon_label = new QLabel(bonScherm);
        bon_label->setObjectName(QString::fromUtf8("bon_label"));
        bon_label->setGeometry(QRect(530, 270, 201, 71));
        bon_label->setFont(font4);
        bon_metBon_button = new QPushButton(bonScherm);
        bon_metBon_button->setObjectName(QString::fromUtf8("bon_metBon_button"));
        bon_metBon_button->setGeometry(QRect(880, 440, 271, 131));
        QSizePolicy sizePolicy1(QSizePolicy::Expanding, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(bon_metBon_button->sizePolicy().hasHeightForWidth());
        bon_metBon_button->setSizePolicy(sizePolicy1);
        bon_metBon_button->setFont(font5);
        bon_zonderBon_button = new QPushButton(bonScherm);
        bon_zonderBon_button->setObjectName(QString::fromUtf8("bon_zonderBon_button"));
        bon_zonderBon_button->setGeometry(QRect(100, 440, 271, 131));
        sizePolicy1.setHeightForWidth(bon_zonderBon_button->sizePolicy().hasHeightForWidth());
        bon_zonderBon_button->setSizePolicy(sizePolicy1);
        bon_zonderBon_button->setFont(font5);
        bon_hoofd_button = new QPushButton(bonScherm);
        bon_hoofd_button->setObjectName(QString::fromUtf8("bon_hoofd_button"));
        bon_hoofd_button->setGeometry(QRect(880, 580, 271, 131));
        sizePolicy.setHeightForWidth(bon_hoofd_button->sizePolicy().hasHeightForWidth());
        bon_hoofd_button->setSizePolicy(sizePolicy);
        bon_hoofd_button->setFont(font5);
        bon_welkom_button = new QPushButton(bonScherm);
        bon_welkom_button->setObjectName(QString::fromUtf8("bon_welkom_button"));
        bon_welkom_button->setGeometry(QRect(100, 580, 271, 131));
        sizePolicy.setHeightForWidth(bon_welkom_button->sizePolicy().hasHeightForWidth());
        bon_welkom_button->setSizePolicy(sizePolicy);
        bon_welkom_button->setFont(font5);
        bon_logo = new QLabel(bonScherm);
        bon_logo->setObjectName(QString::fromUtf8("bon_logo"));
        bon_logo->setGeometry(QRect(30, 20, 211, 201));
        bon_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        bon_logo->setScaledContents(true);
        bon_hoofd_label = new QLabel(bonScherm);
        bon_hoofd_label->setObjectName(QString::fromUtf8("bon_hoofd_label"));
        bon_hoofd_label->setGeometry(QRect(1170, 620, 41, 51));
        bon_hoofd_label->setFont(font3);
        bon_hoofd_label->setFrameShape(QFrame::Box);
        bon_hoofd_label->setFrameShadow(QFrame::Plain);
        bon_hoofd_label->setLineWidth(2);
        bon_metBon_label = new QLabel(bonScherm);
        bon_metBon_label->setObjectName(QString::fromUtf8("bon_metBon_label"));
        bon_metBon_label->setGeometry(QRect(1170, 480, 41, 51));
        bon_metBon_label->setFont(font3);
        bon_metBon_label->setFrameShape(QFrame::Box);
        bon_metBon_label->setFrameShadow(QFrame::Plain);
        bon_metBon_label->setLineWidth(2);
        bon_welkom_label = new QLabel(bonScherm);
        bon_welkom_label->setObjectName(QString::fromUtf8("bon_welkom_label"));
        bon_welkom_label->setGeometry(QRect(40, 620, 41, 51));
        bon_welkom_label->setFont(font3);
        bon_welkom_label->setFrameShape(QFrame::Box);
        bon_welkom_label->setFrameShadow(QFrame::Plain);
        bon_welkom_label->setLineWidth(2);
        bon_zonderBon_label = new QLabel(bonScherm);
        bon_zonderBon_label->setObjectName(QString::fromUtf8("bon_zonderBon_label"));
        bon_zonderBon_label->setGeometry(QRect(40, 480, 41, 51));
        bon_zonderBon_label->setFont(font3);
        bon_zonderBon_label->setFrameShape(QFrame::Box);
        bon_zonderBon_label->setFrameShadow(QFrame::Plain);
        bon_zonderBon_label->setLineWidth(2);
        ATM->addWidget(bonScherm);
        verwerkingsScherm = new QWidget();
        verwerkingsScherm->setObjectName(QString::fromUtf8("verwerkingsScherm"));
        verwerkings_label = new QLabel(verwerkingsScherm);
        verwerkings_label->setObjectName(QString::fromUtf8("verwerkings_label"));
        verwerkings_label->setGeometry(QRect(510, 310, 251, 41));
        verwerkings_label->setFont(font4);
        verwerkings_logo = new QLabel(verwerkingsScherm);
        verwerkings_logo->setObjectName(QString::fromUtf8("verwerkings_logo"));
        verwerkings_logo->setGeometry(QRect(30, 20, 211, 201));
        verwerkings_logo->setPixmap(QPixmap(QString::fromUtf8("ANVI_LOGO.png")));
        verwerkings_logo->setScaledContents(true);
        verwerkings_laadbalk = new QProgressBar(verwerkingsScherm);
        verwerkings_laadbalk->setObjectName(QString::fromUtf8("verwerkings_laadbalk"));
        verwerkings_laadbalk->setGeometry(QRect(520, 360, 251, 31));
        verwerkings_laadbalk->setFont(font1);
        verwerkings_laadbalk->setValue(24);
        ATM->addWidget(verwerkingsScherm);
        QWidget::setTabOrder(welkom_taal_button, welkom_inlog_button);
        QWidget::setTabOrder(welkom_inlog_button, inlog_taal_button);
        QWidget::setTabOrder(inlog_taal_button, inlog_invoerveldPincode);
        QWidget::setTabOrder(inlog_invoerveldPincode, inlog_hoofd_button);
        QWidget::setTabOrder(inlog_hoofd_button, inlog_welkom_button);
        QWidget::setTabOrder(inlog_welkom_button, taal_optieEngels_button);
        QWidget::setTabOrder(taal_optieEngels_button, taal_optieDuits_button);
        QWidget::setTabOrder(taal_optieDuits_button, taal_optieNederlands_button);
        QWidget::setTabOrder(taal_optieNederlands_button, taal_hoofd_of_welkom_of_inlog_button);
        QWidget::setTabOrder(taal_hoofd_of_welkom_of_inlog_button, taal_welkom_button);
        QWidget::setTabOrder(taal_welkom_button, hoofd_taal_button);
        QWidget::setTabOrder(hoofd_taal_button, hoofd_snelPinnen_button);
        QWidget::setTabOrder(hoofd_snelPinnen_button, hoofd_pinKeuze_button);
        QWidget::setTabOrder(hoofd_pinKeuze_button, hoofd_saldo_button);
        QWidget::setTabOrder(hoofd_saldo_button, hoofd_welkom_button);
        QWidget::setTabOrder(hoofd_welkom_button, saldo_pinKeuze_button);
        QWidget::setTabOrder(saldo_pinKeuze_button, saldo_hoofdscherm_button);
        QWidget::setTabOrder(saldo_hoofdscherm_button, saldo_welkom_button);
        QWidget::setTabOrder(saldo_welkom_button, pinKeuze_optie4_button);
        QWidget::setTabOrder(pinKeuze_optie4_button, pinKeuze_optie3_button);
        QWidget::setTabOrder(pinKeuze_optie3_button, pinKeuze_optie2_button);
        QWidget::setTabOrder(pinKeuze_optie2_button, pinKeuze_optie1_button);
        QWidget::setTabOrder(pinKeuze_optie1_button, pinKeuze_optie5_button);
        QWidget::setTabOrder(pinKeuze_optie5_button, pinKeuze_zelfBedragKiezen_button);
        QWidget::setTabOrder(pinKeuze_zelfBedragKiezen_button, pinKeuze_hoofd_button);
        QWidget::setTabOrder(pinKeuze_hoofd_button, pinKeuze_welkom_button);
        QWidget::setTabOrder(pinKeuze_welkom_button, biljetKeuze_biljetOpties1_button);
        QWidget::setTabOrder(biljetKeuze_biljetOpties1_button, biljetKeuze_biljetNietBelangrijk_button);
        QWidget::setTabOrder(biljetKeuze_biljetNietBelangrijk_button, biljetKeuze_hoofd_button);
        QWidget::setTabOrder(biljetKeuze_hoofd_button, biljetKeuze_welkom_button);
        QWidget::setTabOrder(biljetKeuze_welkom_button, bedragKeuze_invoerVeld);
        QWidget::setTabOrder(bedragKeuze_invoerVeld, bedragKeuze_bevestigen_button);
        QWidget::setTabOrder(bedragKeuze_bevestigen_button, bedragKeuze_hoofd_button);
        QWidget::setTabOrder(bedragKeuze_hoofd_button, bedragKeuze_welkom_button);
        QWidget::setTabOrder(bedragKeuze_welkom_button, bon_metBon_button);
        QWidget::setTabOrder(bon_metBon_button, bon_zonderBon_button);
        QWidget::setTabOrder(bon_zonderBon_button, bon_hoofd_button);
        QWidget::setTabOrder(bon_hoofd_button, bon_welkom_button);

        retranslateUi(Login);

        ATM->setCurrentIndex(7);


        QMetaObject::connectSlotsByName(Login);
    } // setupUi

    void retranslateUi(QWidget *Login)
    {
        Login->setWindowTitle(QCoreApplication::translate("Login", "Form", nullptr));
        welkom_taal_button->setText(QCoreApplication::translate("Login", "Languages", nullptr));
        welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">Welcome </p><p align=\"center\">Insert your card</p></body></html>", nullptr));
        welkom_inlog_button->setText(QCoreApplication::translate("Login", "Pas invoer simulatie", nullptr));
        welkom_logo->setText(QString());
        welkom_taal_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">A</p></body></html>", nullptr));
        inlog_voerpin_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">Insert your pin</p></body></html>", nullptr));
        inlog_taal_button->setText(QCoreApplication::translate("Login", "Languages", nullptr));
        inlog_hoofd_button->setText(QCoreApplication::translate("Login", "Confirm", nullptr));
        inlog_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        inlog_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>", nullptr));
        inlog_invoerveldPincode->setText(QString());
        inlog_logo->setText(QString());
        inlog_delete->setText(QString());
        inlog_taal_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">A</p></body></html>", nullptr));
        inlog_delete_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">*</p></body></html>", nullptr));
        inlog_hoofd_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">#</p></body></html>", nullptr));
        inlog_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        taal_optieNederlands_button->setText(QCoreApplication::translate("Login", "Nederlands", nullptr));
        taal_optieEngels_button->setText(QCoreApplication::translate("Login", "English", nullptr));
        taal_optieDuits_button->setText(QCoreApplication::translate("Login", "Deutsch", nullptr));
        taal_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        taal_hoofd_of_welkom_of_inlog_button->setText(QCoreApplication::translate("Login", "Back", nullptr));
        taal_duitsland_vlag->setText(QString());
        taal_engeland_vlag->setText(QString());
        taal_nederland_vlag->setText(QString());
        taal_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">Choose your language</p></body></html>", nullptr));
        taal_logo->setText(QString());
        taal_nederlands_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">A</p></body></html>", nullptr));
        taal_duitsland_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">B</p></body></html>", nullptr));
        taal_engeland_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        taal_back_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">#</p></body></html>", nullptr));
        taal_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        hoofdLabel->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">HoofdScherm</span></p></body></html>", nullptr));
        hoofd_snelPinnen_button->setText(QCoreApplication::translate("Login", "Snel \342\202\25470,-", nullptr));
        hoofd_saldo_button->setText(QCoreApplication::translate("Login", "Balance", nullptr));
        hoofd_pinKeuze_button->setText(QCoreApplication::translate("Login", "Choose amount", nullptr));
        hoofd_taal_button->setText(QCoreApplication::translate("Login", "Languages", nullptr));
        hoofd_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        hoofd_logo->setText(QString());
        hoofd_taal_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">A</p></body></html>", nullptr));
        hoofd_snelPinnen_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">1</p></body></html>", nullptr));
        hoofd_pinKeuze_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">2</p></body></html>", nullptr));
        hoofd_saldo_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">3</p></body></html>", nullptr));
        hoofd_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        saldo_label_wat_is_saldo->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">SaldoScherm</p></body></html>", nullptr));
        saldo_pinKeuze_button->setText(QCoreApplication::translate("Login", "Choose amount", nullptr));
        saldo_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        saldo_hoofdscherm_button->setText(QCoreApplication::translate("Login", "Main page", nullptr));
        saldo_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">Saldo</p></body></html>", nullptr));
        saldo_logo->setText(QString());
        saldo_pinKeuze_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">B</p></body></html>", nullptr));
        saldo_hoofdscherm_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        saldo_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        pinKeuze_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">KeuzeScherm pinnen</p></body></html>", nullptr));
        pinKeuze_optie1_button->setText(QCoreApplication::translate("Login", "\342\202\25420,-", nullptr));
        pinKeuze_optie2_button->setText(QCoreApplication::translate("Login", "\342\202\25450,-", nullptr));
        pinKeuze_optie3_button->setText(QCoreApplication::translate("Login", "\342\202\25470,-", nullptr));
        pinKeuze_optie4_button->setText(QCoreApplication::translate("Login", "\342\202\254100,-", nullptr));
        pinKeuze_optie5_button->setText(QCoreApplication::translate("Login", "\342\202\254120,-", nullptr));
        pinKeuze_zelfBedragKiezen_button->setText(QCoreApplication::translate("Login", "Pick own amount", nullptr));
        pinKeuze_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        pinKeuze_hoofd_button->setText(QCoreApplication::translate("Login", "Main page", nullptr));
        pinKeuze_logo->setText(QString());
        pinKeuze_optie4_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">4</p></body></html>", nullptr));
        pinKeuze_optie3_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">3</p></body></html>", nullptr));
        pinKeuze_optie2_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">2</p></body></html>", nullptr));
        pinKeuze_optie1_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">1</p></body></html>", nullptr));
        pinKeuze_hoofd_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        pinKeuze_optie5_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">5</p></body></html>", nullptr));
        pinKeuze_zelfBedragKiezen_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">B</p></body></html>", nullptr));
        pinKeuze_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        biljetKeuze_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">biljetKeuzeScherm</p></body></html>", nullptr));
        biljetKeuze_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        biljetKeuze_hoofd_button->setText(QCoreApplication::translate("Login", "Main page", nullptr));
        biljetKeuze_biljetNietBelangrijk_button->setText(QCoreApplication::translate("Login", "Not important", nullptr));
        biljetKeuze_biljetOpties1_button->setText(QCoreApplication::translate("Login", "Options banknotes", nullptr));
        biljetKeuze_logo->setText(QString());
        biljetKeuze_hoofd_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        biljetKeuze_biljetNietBelangrijk_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">B</p></body></html>", nullptr));
        biljetKeuze_biljetOpties1_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">A</p></body></html>", nullptr));
        biljetKeuze_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        bedrag_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">BedragKeuzeScherm</p></body></html>", nullptr));
        bedragKeuze_hoofd_button->setText(QCoreApplication::translate("Login", "Main page", nullptr));
        bedragKeuze_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        bedragKeuze_bevestigen_button->setText(QCoreApplication::translate("Login", "Confirm", nullptr));
        bedragKeuze_error_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>", nullptr));
        bedragKeuze_logo->setText(QString());
        bedragKeuze_bevestigen_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">#</p></body></html>", nullptr));
        bedragKeuze_hoofd_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        bedragKeuze_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        bon_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">Bon Scherm</p></body></html>", nullptr));
        bon_metBon_button->setText(QCoreApplication::translate("Login", "Yes", nullptr));
        bon_zonderBon_button->setText(QCoreApplication::translate("Login", "No", nullptr));
        bon_hoofd_button->setText(QCoreApplication::translate("Login", "Main page", nullptr));
        bon_welkom_button->setText(QCoreApplication::translate("Login", "Abort", nullptr));
        bon_logo->setText(QString());
        bon_hoofd_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">C</p></body></html>", nullptr));
        bon_metBon_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">#</p></body></html>", nullptr));
        bon_welkom_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">D</p></body></html>", nullptr));
        bon_zonderBon_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">*</p></body></html>", nullptr));
        verwerkings_label->setText(QCoreApplication::translate("Login", "<html><head/><body><p align=\"center\">verwerkingsScherm</p></body></html>", nullptr));
        verwerkings_logo->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Login: public Ui_Login {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LOGIN_H
